services:
  speedtest-exporter:
    image: kdpuvvadi/speedtest-exporter:latest
    container_name: speedtest-exporter
    ports:
      - "9798:80"
    environment:
      - SPEEDTEST_INTERVAL=1800
    restart: unless-stopped
