{
 "title": "speedtest_exporter",
 "description": "Speedtest Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_download_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_upload_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_jitter_low", "legendFormat": "__auto" },
    { "expr": "speedtest_jitter_high", "legendFormat": "__auto" }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "targets": [
    { "expr": "speedtest_upload_speed", "legendFormat": "__auto" },
    { "expr": "speedtest_download_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 10 },
   "targets": [
    { "expr": "speedtest_jitter", "legendFormat": "__auto" },
    { "expr": "speedtest_latency", "legendFormat": "__auto" },
    { "expr": "speedtest_jitter_low", "legendFormat": "__auto" },
    { "expr": "speedtest_jitter_high", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Monthly Download Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speedtest_download_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Monthly Upload Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speedtest_upload_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "speedtest_server_info", "legendFormat": "__auto" }
   ]
  }
 ]
}