name: Speedtest Exporter

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint Dockerfile and Dry Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Test Multi-Arch Build
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/386 --load -t test-image .

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kdpuvvadi
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kdpuvvadi
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Metadata for Image Tags and Labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            kdpuvvadi/speedtest-exporter
            ghcr.io/kdpuvvadi/speedtest-exporter
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.title=Speedtest Exporter
            org.opencontainers.image.description=Exporter for periodic internet speed tests
            org.opencontainers.image.url=https://github.com/kdpuvvadi/speedtest-exporter
            org.opencontainers.image.source=https://github.com/kdpuvvadi/speedtest-exporter
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
      
      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
